landing/urls.py
from django.urls import path
from landing.views import Index
urlpatterns = [
    path('', Index.as_view(), name='index'),
]

social/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostEditView, PostDeleteView, CommentDeleteView, ProfileView, ProfileEditView
from .views import AddDislike, AddLike, AddFollower, RemoveFollower, UserSearch, ListFollowers, AddCommentLike, AddCommentDislike, CommentReplyView, SharedPostView
from .views import PostNotification, FollowNotification, RemoveNotification, ListThreads, CreateMessage, CreateThread, ThreadView, ThreadNotification,Explore


app_name = "Naija_X"

urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/edit/<int:pk>/', PostEditView.as_view(), name='post-edit'),
    path('post/delete/<int:pk>/', PostDeleteView.as_view(), name='post-delete'),
    path('post/<int:post_pk>/comment/delete/<int:pk>/', CommentDeleteView.as_view(), name='comment-delete'),
    path('post/<int:pk>/like', AddLike.as_view(), name='like'),
    path('post/<int:pk>/dislike', AddDislike.as_view(), name='dislike'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/edit/<int:pk>/', ProfileEditView.as_view(), name='profile-edit'),
    path('profile/<int:pk>/followers/add', AddFollower.as_view(), name='add-follower'),
    path('profile/<int:pk>/followers/remove', RemoveFollower.as_view(), name='remove-follower'),
    path('profile/<int:pk>/followers/', ListFollowers.as_view(), name='list-followers'),
    path('search/', UserSearch.as_view(), name='profile-search'),
    path('profile/<int:pk>/followers', ListFollowers.as_view(), name='followers-list'),
    path('post/<int:post_pk>/comment/<int:pk>/like', AddCommentLike.as_view(), name='comment-like'),
    path('post/<int:post_pk>/comment/<int:pk>/dislike', AddCommentDislike.as_view(), name='comment-dislike'),
    path('post/<int:post_pk>/comment/reply/<int:pk>', CommentReplyView.as_view(), name='comment-reply'),
    path('notification/<int:notification_pk>/post/<int:object_pk>', PostNotification.as_view(), name='post-notification'),
    path('notification/<int:notification_pk>/follow/<int:object_pk>', FollowNotification.as_view(), name='follow-notification'),
    path('notification/delete/<int:notification_pk>', RemoveNotification.as_view(), name='notification-delete'),
    path('inbox/', ListThreads.as_view(), name='inbox'),
    path('inbox/create-thread', CreateThread.as_view(), name='create-thread'),
    path('inbox/<int:pk>/', ThreadView.as_view(), name='thread'),
    path('inbox/<int:pk>/create-message/', CreateMessage.as_view(), name='create-message'),
    path('notification/<int:notification_pk>/thread/<int:object_pk>', ThreadNotification.as_view(), name='thread-notification'),
    path('post/<int:pk>/share', SharedPostView.as_view(), name='share-post'),
    path('explore/', Explore.as_view(), name='explore'),
]

social_media/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('landing.urls')),
    path('social/', include('social.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/models.py
from django.db import models

# Create your models here.

landing/views.py
from django.shortcuts import render
from django.views import View





class Index(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'landing/index.html')

landing/templates/landing/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="{% static 'styles.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    
    
    
    <title>Naija-X</title>
  </head>
  <body>
    {% include 'landing/navbar.html' %}
    {% block content %}
    {% endblock content %}
    <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
    <script type="text/javascript" src="{% static 'js/social.js' %}"></script>
  </body>
</html>

landing/templates/landing/index.html
{% extends 'landing/base.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-10 col-sm-12 text-center">
            <h1 class="display-2" style="color:#198754">Connect With Your Friends!</h1>
            <p class="mt-3 lead">Follow people who interest you, stay up to date on the latest news and join conversations with your friends!</p>
            <div class="d-flex justify-content-center mt-5">
                <a href="{% url 'account_login' %}" class="btn btn-light mr-2" style="color:#198754 ">Log In</a>
                <a href="{% url 'account_signup' %}" class="btn btn-dark" style="background-color:#198754 ">Register</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

landing/templates/landing/navbar.html
{% load custom_tags %}


<div class="container gx-0" >
  <nav class="navbar navbar-expand-lg navbar-light" >
    <div class="container-fluid" >
        <a class="navbar-brand" 
          {% if user.is_authenticated %}
            href="{% url 'Naija_X:post-list' %}"
          {% else %}
          href="{% url 'index' %}"
          {% endif %}
          style="color:#198754"
        >
            <i class="fas fa-comment"></i>
            Naija X
          </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        </ul>
        <form class="d-flex" method="GET" action="{% url 'Naija_X:profile-search' %}">
          <div class="input-group">
              <span class="input-group-text" id="basic-addon1">@</span>
              <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1" name='query' value="{{ request.GET.query }}">
              <button style="border: none; background-color: transparent; box-shadow: none" type="submit"><i class="fas fa-search"></i></button>
          </div>
        </form>
          {% if user.is_authenticated %}
            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-dark" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false"><i class="fas fa-user"></i></a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'Naija_X:profile' request.user.profile.pk %}">Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'account_logout' %}">Sign Out</a></li>
              </ul>
            </div>
            <div class="nav-item">
              {% show_notifications %}
            </div>
            <div class="nav-item inbox-icon-container">
              <a href="{% url 'Naija_X:inbox' %}" class="inbox-icon"><i class="far fa-paper-plane"></i></a>
            </div>
          {% endif %}
      </div>
    </div>
  </nav>
</div>