social/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostEditView, PostDeleteView, CommentDeleteView, ProfileView, ProfileEditView
from .views import AddDislike, AddLike, AddFollower, RemoveFollower, UserSearch, ListFollowers, AddCommentLike, AddCommentDislike, CommentReplyView, SharedPostView
from .views import PostNotification, FollowNotification, RemoveNotification, ListThreads, CreateMessage, CreateThread, ThreadView, ThreadNotification,Explore


app_name = "Naija_X"

urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/edit/<int:pk>/', PostEditView.as_view(), name='post-edit'),
    path('post/delete/<int:pk>/', PostDeleteView.as_view(), name='post-delete'),
    path('post/<int:post_pk>/comment/delete/<int:pk>/', CommentDeleteView.as_view(), name='comment-delete'),
    path('post/<int:pk>/like', AddLike.as_view(), name='like'),
    path('post/<int:pk>/dislike', AddDislike.as_view(), name='dislike'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/edit/<int:pk>/', ProfileEditView.as_view(), name='profile-edit'),
    path('profile/<int:pk>/followers/add', AddFollower.as_view(), name='add-follower'),
    path('profile/<int:pk>/followers/remove', RemoveFollower.as_view(), name='remove-follower'),
    path('profile/<int:pk>/followers/', ListFollowers.as_view(), name='list-followers'),
    path('search/', UserSearch.as_view(), name='profile-search'),
    path('profile/<int:pk>/followers', ListFollowers.as_view(), name='followers-list'),
    path('post/<int:post_pk>/comment/<int:pk>/like', AddCommentLike.as_view(), name='comment-like'),
    path('post/<int:post_pk>/comment/<int:pk>/dislike', AddCommentDislike.as_view(), name='comment-dislike'),
    path('post/<int:post_pk>/comment/reply/<int:pk>', CommentReplyView.as_view(), name='comment-reply'),
    path('notification/<int:notification_pk>/post/<int:object_pk>', PostNotification.as_view(), name='post-notification'),
    path('notification/<int:notification_pk>/follow/<int:object_pk>', FollowNotification.as_view(), name='follow-notification'),
    path('notification/delete/<int:notification_pk>', RemoveNotification.as_view(), name='notification-delete'),
    path('inbox/', ListThreads.as_view(), name='inbox'),
    path('inbox/create-thread', CreateThread.as_view(), name='create-thread'),
    path('inbox/<int:pk>/', ThreadView.as_view(), name='thread'),
    path('inbox/<int:pk>/create-message/', CreateMessage.as_view(), name='create-message'),
    path('notification/<int:notification_pk>/thread/<int:object_pk>', ThreadNotification.as_view(), name='thread-notification'),
    path('post/<int:pk>/share', SharedPostView.as_view(), name='share-post'),
    path('explore/', Explore.as_view(), name='explore'),
]

social_media/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('landing.urls')),
    path('social/', include('social.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/forms.py
from django import forms
from .models import Post, Comment, MessageModel


class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result

class PostForm(forms.ModelForm):
    body = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'rows': '3',
            'placeholder': 'Say Something...'
            }))

    image = MultipleFileField(label='Select files', required=False)

    class Meta:
        model = Post
        fields = ['body']

class CommentForm(forms.ModelForm):
    comment = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'rows': '3',
            'placeholder': 'Say Something...'
            }))

    class Meta:
        model = Comment
        fields = ['comment']

class ThreadForm(forms.Form):
    username = forms.CharField(label='', max_length=100)

class MessageForm(forms.ModelForm):
    body = forms.CharField(label='', max_length=1000)

    image = forms.ImageField(required=False)

    class Meta:
        model = MessageModel
        fields = ['body', 'image']


class ShareForm(forms.Form):
    body = forms.CharField(
    label='',
    widget=forms.Textarea(attrs={
        'rows': '3',
        'placeholder': 'Say Something...'
    }))        


class ExploreForm(forms.Form):
  query = forms.CharField(
  label='',
  widget=forms.TextInput(attrs={
    'placeholder': 'Explore tags'
    })
  )    

social/views.py
from django.shortcuts import render,redirect, HttpResponse
from django.utils import timezone
from django.urls import reverse_lazy
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.views import View
from django.views.generic.edit import UpdateView, DeleteView
from .models import Post, Comment, UserProfile, Notification, ThreadModel, MessageModel, Image, Tag
from .forms import PostForm, CommentForm, ThreadForm, MessageForm, ShareForm, ExploreForm
from django.http import HttpResponseRedirect
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.models import User

class PostListView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        logged_in_user = request.user
        posts = Post.objects.all().order_by('-created_on')
        share_form = ShareForm()
        form = PostForm()
        context = {
            'post_list': posts,
            'form': form,
            'shareform': share_form,
        }
        return render(request, 'social/post_list.html', context)
    def post(self, request, *args, **kwargs):
        logged_in_user = request.user
        posts = Post.objects.all().order_by('-created_on')
        form = PostForm(request.POST, request.FILES)
        files = request.FILES.getlist('image')
        share_form = ShareForm()  
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()    
        for f in files:
            img = Image(image=f)
            img.save()
            new_post.image.add(img)

        new_post.create_tags()
        new_post.save()

        context = {
            'post_list': posts,
            'form': form,
            'shareform': share_form,
            }
        return render(request, 'social/post_list.html', context)
class PostDetailView(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)
        form = CommentForm()
        comments = Comment.objects.filter(post=post).order_by('-created_on')
        context = {
            'post': post,
            'form': form,
            'comments': comments,
        }
        return render(request, 'social/post_detail.html', context)
    def post(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.post = post
            new_comment.save()
            new_comment.create_tags()
            return redirect('Naija_X:post-detail')

        
        comments = Comment.objects.filter(post=post).order_by('-created_on')
        notification = Notification.objects.create(notification_type=2, from_user=request.user, to_user=post.author, post=post)        
        context = {
            'post': post,
            'form': form,
            'comments': comments,
        }
        return render(request, 'social/post_detail.html', context)
class PostEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['body']
    template_name = 'social/post_edit.html'
    
    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('Naija_X:post-detail', kwargs={'pk': pk})
    
    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author
class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'social/post_delete.html'
    success_url = reverse_lazy('Naija_X:post-list')
    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author
class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    template_name = 'social/comment_delete.html'
    def get_success_url(self):
        pk = self.kwargs['post_pk']
        return reverse_lazy('Naija_X:post-detail', kwargs={'pk': pk})
    def test_func(self):
        comment = self.get_object()
        return self.request.user == comment.author
    

class ProfileView(View):
    def get(self, request, pk, *args, **kwargs):
        profile = UserProfile.objects.get(pk=pk)
        user = profile.user
        posts = Post.objects.filter(author=user).order_by('-created_on')
        followers = profile.followers.all()
        is_following = False
        for follower in followers:
            if follower == request.user:
                is_following = True
                break
            else:
                is_following = False
        number_of_followers = len(followers)
        context = {
            'user': user,
            'profile': profile,
            'posts': posts,
            'is_following': is_following,
            'number_of_followers': number_of_followers,
        }
        return render(request, 'social/profile.html', context)

     
class AddFollower(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        profile = UserProfile.objects.get(pk=pk)
        profile.followers.add(request.user)
        notification = Notification.objects.create(notification_type=3, from_user=request.user, to_user=profile.user)        
        return redirect('profile', pk=profile.pk)    

class RemoveFollower(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        profile = UserProfile.objects.get(pk=pk)
        profile.followers.remove(request.user)
        return redirect('profile', pk=profile.pk)           

class ProfileEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = UserProfile
    fields = ['name', 'bio', 'birth_date', 'location', 'picture']
    template_name = 'social/profile_edit.html'
    
    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('Naija_X:profile', kwargs={'pk': pk})
    
    def test_func(self):
        profile = self.get_object()
        return self.request.user == profile.user    

class AddLike(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)
        is_dislike = False
        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break
        if is_dislike:
            post.dislikes.remove(request.user)
        is_like = False
        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break
        if not is_like: 
            post.likes.add(request.user)
            notification = Notification.objects.create(notification_type=1, from_user=request.user, to_user=post.author, post=post)
        
        if is_like:
            post.likes.remove(request.user)
        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)
    
class AddDislike(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)
        is_like = False
        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break
        if is_like:
            post.likes.remove(request.user)
        is_dislike = False
        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break
        if not is_dislike: 
            post.dislikes.add(request.user)
        
        if is_dislike:
            post.dislikes.remove(request.user)
        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)
    
class UserSearch(View):
    def get(self, request, *args, **kwargs):
        query = self.request.GET.get('query')
        profile_list = UserProfile.objects.filter(
            Q(user__username__icontains=query)
        )
        context = {
            'profile_list': profile_list
        }
        return render(request, 'social/search.html', context)    
    
class ListFollowers(View):
    def get(self, request, pk, *args, **kwargs):
        profile = UserProfile.objects.get(pk=pk)
        followers = profile.followers.all()
        context = {
            'profile': profile,
            'followers': followers,
        }
        return render(request, 'social/followers_list.html', context)    
    
class AddCommentLike(LoginRequiredMixin, View):
    def post(self, request, post_pk, pk, *args, **kwargs):
        comment = Comment.objects.get(pk=pk)
        is_dislike = False
        for dislike in comment.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break
        if is_dislike:
            comment.dislikes.remove(request.user)
        is_like = False
        for like in comment.likes.all():
            if like == request.user:
                is_like = True
                break
        if not is_like: 
            comment.likes.add(request.user)
            notification = Notification.objects.create(notification_type=1, from_user=request.user, to_user=comment.author, comment=comment)
        
        if is_like:
            comment.likes.remove(request.user)
        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)
    
class AddCommentDislike(LoginRequiredMixin, View):
    def post(self, request, post_pk, pk, *args, **kwargs):
        comment = Comment.objects.get(pk=pk)
        is_like = False
        for like in comment.likes.all():
            if like == request.user:
                is_like = True
                break
        if is_like:
            comment.likes.remove(request.user)
        is_dislike = False
        for dislike in comment.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break
        if not is_dislike: 

social/templates/social/create_thread.html
{% extends 'landing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-12 p-5">
			<a href="{% url 'Naija_X:inbox' %}" class="btn btn-light">Back to Your Inbox</a>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12 p-5">
			<h3>Start a Conversation!</h3>
		</div>
	</div>

	<div class="row justify-content-center mt-3 mb-5">
		<div class="col-md-5 col-sm-12">
		  {% if messages %}
		  {% for message in messages %}
		  <div class="alert alert-danger" role="alert">
		  {{ message }}
		  </div>
		{% endfor %}
		{% endif %}
		<form method="POST">
		  {% csrf_token %}
		  <p>Enter the username for the person you would like to talk to.</p>
		  {{ form | crispy }}
		  <div class="d-grid gap-2">
			<button type="submit" class="btn btn-success mt-3">Continue</button>
		  </div>
		</form>
		</div>
	  </div>
</div>

{% endblock content %}

social/templates/social/inbox.html
{% extends 'landing/base.html' %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-12 p-5">
			<h3>Your Conversations</h3>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12 p-5">
			<form method="GET" action="{% url 'Naija_X:create-thread' %}">
				<button class="btn btn-light p-3" type="submit">Start a Conversation</button>
			</form>
		</div>
	</div>

	{% for thread in threads.all %}
	<div class="row mb-3">
		<div class="card col-md-12 p-5 shadow-sm">
		  <h5><i class="far fa-envelope inbox-icon"></i>@{{ thread.receiver }}</h5>
		  <a class="stretched-link" href="{% url 'Naija_X:thread' thread.pk %}"></a>
		</div>
	  </div>
	{% endfor %}
</div>

{% endblock content %}

social/templates/social/post_detail.html
{% extends 'landing/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-5 col-sm-6">
            <a href="{% url 'Naija_X:post-list' %}" class="btn btn-light">Back To Feed</a>
        </div>
    </div>

    <div class="row justify-content-center mt-3">
        <div class="col-md-5 col-sm-12 border-bottom">
                <div>
                    <a href="{% url 'Naija_X:profile' post.author.profile.pk %}">
                        <img class="round-circle post-img" height="30" width="30" src="{{ post.author.profile.picture.url }}" />
                    </a>
                    <p class="post-text">
                        <a class="text-primary post-link" href="{% url 'Naija_X:profile' post.author.profile.pk %}">@{{ post.author }}</a> {{ post.created_on }}
                    </p>
                </div>
                {% if request.user == post.author %}
                    <a href="{% url 'Naija_X:post-edit' post.pk %}" class="edit-color"><i class="far fa-edit"></i></a>
                    <a href="{% url 'Naija_X:post-delete' post.pk %}" class="edit-color"><i class="fas fa-trash"></i></a>
                {% endif %}
                {% if post.image.count > 0 %}
                <div class="row">
                {% for img in post.image.all %}
                <div class="col-md-4">
                    <img src="{{ img.image.url }}" class="post-image" />
                </div>
                {% endfor %}
                </div>
                {% endif %}
                <p>{{ post.body }}</p>

            <div class="d-flex flex-row">
                <form method="POST" action="{% url 'Naija_X:like' post.pk %}">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button class="remove-default-btn" type="submit">
                        <i class="far fa-thumbs-up"> <span>{{ post.likes.all.count }}</span></i>
                    </button>
                </form>

                <form method="POST" action="{% url 'Naija_X:dislike' post.pk %}">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button class="remove-default-btn" type="submit">
                        <i class="far fa-thumbs-down"> <span>{{ post.dislikes.all.count }}</span></i>
                    </button>
                </form>
        </div>
        </div>
    </div>

    <div class="row justify-content-center mt-3 mb-5">
        <div class="col-md-5 col-sm-12">
            <form method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="d-grid gap-2">
                    <button class="btn btn-success mt-3">Submit!</button>
                </div>
            </form>
        </div>
    </div>
    {% for comment in comments %}
    {% if comment.is_parent %}
    <div class="row justify-content-center mt-3 mb-5">
        <div class="col-md-5 col-sm-12 border-bottom">
            <p>
                <div>
                    <a href="{% url 'Naija_X:profile' comment.author.profile.pk %}">
                        <img class="round-circle post-img" height="30" width="30" src="{{ comment.author.profile.picture.url }}" />
                    </a>
                    <p class="post-text">
                        <a class="text-primary post-link" href="{% url 'Naija_X:profile' comment.author.profile.pk %}">@{{ comment.author }}</a> {{ comment.created_on }}
                    </p>
                </div>
                {% if request.user == comment.author %}
                    <a href="{% url 'comment-delete' post.pk comment.pk %}" class="edit-color"><i class="fas fa-trash"></i></a>
                {% endif %}
            </p>
            <p>{{ comment.comment }}</p>

            <div class="d-flex flex-row">
                <form method="POST" action="{% url 'Naija_X:comment-like' post.pk comment.pk %}">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button class="remove-default-btn" type="submit">
                        <i class="far fa-thumbs-up"> <span>{{ comment.likes.all.count }}</span></i>
                    </button>
                </form>

                <form method="POST" action="{% url 'Naija_X:comment-dislike' post.pk comment.pk %}">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button class="remove-default-btn" type="submit">
                        <i class="far fa-thumbs-down"> <span>{{ comment.dislikes.all.count }}</span></i>
                    </button>
                </form>
                <div>
                    <button class="remove-default-btn"><i class="far fa-comment-dots" onclick="commentReplyToggle('{{ comment.pk }}')"></i></button>
                </div>
        </div>
        </div>
    </div>
    <div class="row justify-content-center mt-3 mb-5 d-none" id="{{ comment.pk }}">
        <div class="col-md-5 col-sm-12">
            <form method="POST" action="{% url 'Naija_X:comment-reply' post.pk comment.pk %}">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="d-grid gap-2">
                    <button class="btn btn-success mt-3">Submit!</button>
                </div>
            </form>
        </div>
    </div>

    {% for child_comment in comment.children %}
    <div class="row justify-content-center mt-3 mb-5 child-comment">
        <div class="col-md-5 col-sm-12 border-bottom">
            <p>
                <div>
                    <a href="{% url 'Naija_X:profile' child_comment.author.profile.pk %}">
                        <img class="round-circle post-img" height="30" width="30" src="{{ child_comment.author.profile.picture.url }}" />
                    </a>
                    <p class="post-text">
                        <a class="text-primary post-link" href="{% url 'Naija_X:profile' child_comment.author.profile.pk %}">@{{ child_comment.author }}</a> {{ child_comment.created_on }}
                    </p>
                </div>
                {% if request.user == child_comment.author %}
                    <a href="{% url 'Naija_X:comment-delete' post.pk child_comment.pk %}" class="edit-color"><i class="fas fa-trash"></i></a>
                {% endif %}
            </p>
            <p>{{ child_comment.comment }}</p>
        </div>
    </div>
    {% endfor %}
    {% endif %}
    {% endfor %}
</div>
{% endblock content %}

social/templates/social/profile.html
{% extends 'landing/base.html' %}

{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-3 col-sm-6">
            <a href="{% url 'Naija_X:post-list' %}" class="btn btn-light">Back to Feed</a>
        </div>
    </div>

    <div class="row justify-content-center mt-5">
        <div class="card shadow-sm col-md-8 col-sm-12 border-bottom px-5 pt-3">
            <div class="text-center">
                <img src="{{ profile.picture.url }}" class="rounded-circle" width="100" height="100" />
                {% if profile.name %}
                <h3 class="py-4">{{ profile.name }}
                    <span>
                        {% if request.user == user %}
                            <a href="{% url 'Naija_X:profile-edit' profile.pk %}" class="edit-color"><i class="far fa-edit"></i></a>
                        {% endif %}
                    </span>
                    {% else %}
                    <h3 class="py-4">{{ user.username }}
                        <span>
                            {% if request.user == user %}
                                <a href="{% url 'Naija_X:profile-edit' profile.pk %}" class="edit-color"><i class="far fa-edit"></i></a>
                            {% endif %}
                        </span>
                    </h3>
                    {% endif %}
                </h3>
            </div>

            {% if profile.bio %}
            <p>{{ profile.bio }}</p>
            {% endif %}

            <div class="mb-3">
                <a href="{% url 'Naija_X:list-followers' profile.pk %}" class="post-link">Followers: {{ number_of_followers }}</a>
                
            </div>
        </div>
    </div>

    <div class="row justify-content-center mt-5">
        <div class="card shadow-sm col-md-8 col-sm-12 border-bottom px-5 py-3">
            {% if profile.location %}
            <p>Location: {{ profile.location }}</p>
            {% endif %}

            {% if profile.birth_date %}
            <p>Birthday: {{ profile.birth_date }}</p>
            {% endif %}

            {% if user == request.user %}
                {% else %}
                {% if is_following %}
                    <form method="POST" action="{% url 'Naija_X:remove-follower' profile.pk %}">
                        {% csrf_token %}
                        <button class="btn btn-outline-danger" type="submit">Unfollow</button>
                    </form>
                    {% else %}
                    <form method="POST" action="{% url 'Naija_X:add-follower' profile.pk %}">
                        {% csrf_token %}
                        <button class="btn btn-outline-success" type="submit">Follow</button>
                    </form>
                {% endif %}
            {% endif %}
        </div>
    </div>

    {% for post in posts %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-8 col-sm-12 border-bottom">
            <div>
                <a href="{% url 'Naija_X:profile' post.author.profile.pk %}">
                    <img class="round-circle post-img" height="30" width="30" src="{{ post.author.profile.picture.url }}" />
                </a>
                <p class="post-text">
                    <a class="text-primary post-link" href="{% url 'Naija_X:profile' post.author.profile.pk %}">@{{ post.author }}</a> {{ post.created_on }}
                </p>
            </div>
            <div class="position-relative">
                {% if post.image.count > 0 %}
                <div class="row">
                {% for img in post.image.all %}
                <div class="col-md-4">
                    <img src="{{ img.image.url }}" class="post-image" />
                </div>
                {% endfor %}
                </div>
                {% endif %}
                <p>{{ post.body }}</p>
                <a class="stretched-link" href="{% url 'Naija_X:post-detail' post.pk %}"></a>
              </div>
            <div class="d-flex flex-row">
                <form method="POST" action="{% url 'Naija_X:like' post.pk %}">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button class="remove-default-btn" type="submit">
                        <i class="far fa-thumbs-up"> <span>{{ post.likes.all.count }}</span></i>
                    </button>
                </form>

                <form method="POST" action="{% url 'Naija_X:dislike' post.pk %}">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button class="remove-default-btn" type="submit">
                        <i class="far fa-thumbs-down"> <span>{{ post.dislikes.all.count }}</span></i>
                    </button>
                </form>
        </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

social/templates/social/show_notifications.html
<div class="dropdown">
	<span class="badge bg-primary notification-badge" onclick="showNotifications()">{{ notifications.count }}</span>
	<div class="dropdown-content d-none" id="notification-container">
		{% for notification in notifications %}
			{% if notification.post %}
				{% if notification.notification_type == 1 %}
				<div class="dropdown-item-parent">
					<a href="{% url 'Naija_X:post-notification' notification.pk notification.post.pk %}">@{{ notification.from_user }} liked your post</a>
					<span class="dropdown-item-close" onclick="removeNotification(`{% url 'Naija_X:notification-delete' notification.pk %}`, `{{ request.path }}`)">&times;</span>
				</div>
				{% elif notification.notification_type == 2 %}
				<div class="dropdown-item-parent">
					<a href="{% url 'Naija_X:post-notification' notification.pk notification.post.pk %}">@{{ notification.from_user }} commented on your post</a>
					<span class="dropdown-item-close" onclick="removeNotification(`{% url 'Naija_X:notification-delete' notification.pk %}`, `{{ request.path }}`)">&times;</span>
				</div>
				{% endif %}
			{% elif notification.comment %}
				{% if notification.notification_type == 1 %}
				<div class="dropdown-item-parent">
					<a href="{% url 'Naija_X:post-notification' notification.pk notification.comment.post.pk %}">@{{ notification.from_user }} liked your comment</a>
					<span class="dropdown-item-close" onclick="removeNotification(`{% url 'Naija_X:notification-delete' notification.pk %}`, `{{ request.path }}`)">&times;</span>
				</div>
				{% elif notification.notification_type == 2 %}
				<div class="dropdown-item-parent">
					<a href="{% url 'Naija_X:post-notification' notification.pk notification.comment.post.pk %}">@{{ notification.from_user }} replied to your comment</a>
					<span class="dropdown-item-close" onclick="removeNotification(`{% url 'Naija_X:notification-delete' notification.pk %}`, `{{ request.path }}`)">&times;</span>
				</div>
				{% endif %}
			{% elif notification.thread %}
				<div class="dropdown-item-parent">
					<a href="{% url 'Naija_X:thread-notification' notification.pk notification.thread.pk %}">@{{ notification.from_user }} sent you a message</a>
					<span class="dropdown-item-close" onclick="removeNotification(`{% url 'Naija_X:notification-delete' notification.pk %}`, `{{ request.path }}`)">&times;</span>
				</div>
			{% else %}
			<div class="dropdown-item-parent">
					<a href="{% url 'Naija_X:follow-notification' notification.pk notification.from_user.profile.pk %}">@{{ notification.from_user }} has started following you</a>
					<span class="dropdown-item-close" onclick="removeNotification(`{% url 'Naija_X:notification-delete' notification.pk %}`, `{{ request.path }}`)">&times;</span>
				</div>
			{% endif %}
			{% endfor %}
		</div>
	</div>